<?php

$dictionary['FiasAddrObj'] = array(
	'table' => 'fiasaddrobj',
	'audited' => true,
	'duplicate_merge' => true,
	'fields' => array(
		'name' => array(
			'name' => 'name',
			'vname' => 'LBL_NAME',
			'type' => 'name',
			'link' => true,
			'dbType' => 'varchar',
			'len' => '255',
			'unified_search' => false,
			'full_text_search' => array(
				'boost' => 3,
			),
			'required' => true,
			'importable' => 'required',
			'duplicate_merge' => 'disabled',
			'merge_filter' => 'disabled',
			'massupdate' => 0,
			'no_default' => false,
			'duplicate_merge_dom_value' => '0',
			'reportable' => true,
			'isnull' => false,
		),
		'shortname' => array(
			'required' => false,
			'name' => 'shortname',
			'vname' => 'LBL_SHORTNAME',
			'type' => 'varchar',
			'massupdate' => 0,
			'no_default' => false,
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
			'reportable' => true,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'len' => '10',
			'isnull' => true,
		),
		'postalcode' => array(
			'required' => false,
			'name' => 'postalcode',
			'vname' => 'LBL_POSTALCODE',
			'type' => 'varchar',
			'massupdate' => 0,
			'no_default' => false,
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
			'reportable' => true,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'len' => '6',
			'isnull' => true,
		),
		'aolevel' => array(
			'required' => true,
			'name' => 'aolevel',
			'vname' => 'LBL_AOLEVEL',
			'type' => 'int',
			'massupdate' => 0,
			'no_default' => false,
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
			'reportable' => true,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'len' => '10',
			'isnull' => false,
		),
		'code' => array (
			'required' => false,
			'name' => 'code',
			'vname' => 'LBL_CODE',
			'type' => 'varchar',
			'massupdate' => 0,
			'no_default' => false,
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
			'reportable' => true,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'len' => '17',
			'isnull' => true,
		),
		'plaincode' => array (
			'required' => false,
			'name' => 'plaincode',
			'vname' => 'LBL_PLAINCODE',
			'type' => 'varchar',
			'massupdate' => 0,
			'no_default' => false,
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
			'reportable' => true,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'len' => '15',
			'isnull' => true,
		),
		'aoid' => array (
			'required' => true,
			'name' => 'aoid',
			'vname' => 'LBL_AOID',
			'type' => 'id',
			'massupdate' => 0,
			'no_default' => false,
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
			'reportable' => false,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'len' => '36',
			'isnull' => false,
		),
		'updatedate' => array(
			'required' => true,
			'name' => 'updatedate',
			'vname' => 'LBL_UPDATEDATE',
			'type' => 'date',
			'massupdate' => 0,
			'no_default' => false,
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
			'reportable' => true,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'isnull' => false,
		),
		'fullname' => array(
			'name' => 'fullname',
			'vname' => 'LBL_FULLNAME',
			'type' => 'varchar',
			'len' => '1000',
			'unified_search' => false,
			'full_text_search' => array(
				'boost' => 3,
			),
			'required' => false,
			'importable' => true,
			'duplicate_merge' => 'disabled',
			'merge_filter' => 'disabled',
			'massupdate' => 0,
			'no_default' => false,
			'duplicate_merge_dom_value' => '0',
			'reportable' => true,
			'isnull' => true,
		),
		'fiascode' => array(
			'name' => 'fiascode',
			'vname' => 'LBL_FIASCODE',
			'type' => 'char',
			'len' => '26',
			'unified_search' => false,
			'full_text_search' => array(
				'boost' => 3,
			),
			'required' => false,
			'importable' => true,
			'duplicate_merge' => 'enabled',
			'merge_filter' => 'disabled',
			'massupdate' => 0,
			'duplicate_merge_dom_value' => '0',
			'reportable' => true,
			'isnull' => true,
		),
	),
	'relationships' => array(
	),
	'indices' => array(
		array(
			'name' => 'idx_fiasaddrobj_aoid',
			'type' => 'unique', 
			'fields' => array('aoid'),
		),
		array(
			'name' => 'idx_fiasaddrobj_name',
			'type' => 'index', 
			'fields' => array('name'),
		),
		array(
			'name' => 'idx_fiasaddrobj_fullname',
			'type' => 'index', 
			'fields' => array('fullname'),
		),
		array(
			'name' => 'idx_fiasaddrobj_aolevel_fiascode',
			'type' => 'index', 
			'fields' => array('aolevel', 'fiascode'),
		),
	),
	'optimistic_locking' =>true,
	'unified_search' => true,
);

if (!class_exists('VardefManager')) {
	require_once('include/SugarObjects/VardefManager.php');
}

VardefManager::createVardef('FiasAddrObj', 'FiasAddrObj', array('basic','assignable'));
?>
