<?php

$dictionary['FiasHouse'] = array(
	'table' => 'fiashouse',
	'audited' => true,
	'duplicate_merge' => true,
	'fields' => array(
		'name' => array(
			'name' => 'name',
			'vname' => 'LBL_NAME',
			'type' => 'name',
			'link' => true,
			'dbType' => 'varchar',
			'len' => '20',
			'unified_search' => false,
			'full_text_search' => array(
				'boost' => 3,
			),
			'required' => false,
			'importable' => 'required',
			'duplicate_merge' => 'disabled',
			'merge_filter' => 'disabled',
			'massupdate' => 0,
			'no_default' => false,
			'duplicate_merge_dom_value' => '0',
			'reportable' => true,
			'isnull' => true,
		),
		'postalcode' => array(
			'required' => false,
			'name' => 'postalcode',
			'vname' => 'LBL_POSTALCODE',
			'type' => 'varchar',
			'massupdate' => 0,
			'no_default' => false,
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
			'reportable' => true,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'len' => '6',
			'isnull' => true,
		),
		'updatedate' => array(
			'required' => true,
			'name' => 'updatedate',
			'vname' => 'LBL_UPDATEDATE',
			'type' => 'date',
			'massupdate' => 0,
			'no_default' => false,
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
			'reportable' => true,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'isnull' => false,
		),
		'buildnum' => array(
			'required' => false,
			'name' => 'buildnum',
			'vname' => 'LBL_BUILDNUM',
			'type' => 'varchar',
			'massupdate' => 0,
			'no_default' => false,
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
			'reportable' => true,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'len' => '10',
			'isnull' => true,
		),
		'strucnum' => array(
			'required' => false,
			'name' => 'strucnum',
			'vname' => 'LBL_STRUCNUM',
			'type' => 'varchar',
			'massupdate' => 0,
			'no_default' => false,
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
			'reportable' => true,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'len' => '10',
			'isnull' => true,
		),
		'houseid' => array (
			'required' => true,
			'name' => 'houseid',
			'vname' => 'LBL_HOUSEID',
			'type' => 'id',
			'massupdate' => 0,
			'no_default' => false,
			'importable' => 'required',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
			'reportable' => false,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'len' => '36',
			'isnull' => false,
		),
		'counter' => array(
			'required' => false,
			'name' => 'counter',
			'vname' => 'LBL_COUNTER',
			'type' => 'int',
			'massupdate' => 0,
			'no_default' => false,
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
			'reportable' => true,
			'unified_search' => false,
			'merge_filter' => 'disabled',
			'len' => '4',
			'isnull' => true,
		),
	),
	'relationships' => array(
	),
	'indices' => array(
		array(
			'name' => 'idx_fiashouse_houseid',
			'type' => 'unique', 
			'fields' => array('houseid'),
		),
		/*array(
			'name' => 'idx_fiashouse_aoguid',
			'type' => 'index', 
			'fields' => array('aoguid'),
		),*/
		array(
			'name' => 'idx_fiashouse_housenum',
			'type' => 'index', 
			'fields' => array('name'),
		),
	),
);

if (!class_exists('VardefManager')) {
	require_once('include/SugarObjects/VardefManager.php');
}

VardefManager::createVardef('FiasHouse', 'FiasHouse', array('basic','assignable'));
?>